name: wallet_tracker
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2



  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5


  expense_repository:
    path: packages/expense_repository
  uuid: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
